name: Export course lesson data report to BigQuery

on: workflow_dispatch

jobs:
  export:
    runs-on: ubuntu-20.04
    container: google/cloud-sdk:latest
    steps:
      - name: Auth with gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_BASE64 }}

      - name: Install CloudFoundry CLI
        shell: bash
        run: |
          apt-get install -y wget postgresql-client
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          apt-get update
          apt-get install cf7-cli

      - name: Generate course lesson data csv
        shell: bash
        env:
          PAAS_ORGANISATION: dfe
          PAAS_SPACE: earlycareers-framework-dev
          ENV_STUB: dev
          APP_NAME: ecf-engage-and-learn
          CF_USERNAME: ${{ secrets.GOVPAAS_DEV_USERNAME }}
          CF_PASSWORD: ${{ secrets.GOVPAAS_DEV_PASSWORD }}
        run: |
          cf api https://api.london.cloud.service.gov.uk
          cf auth
          cf target -o "${{ env.PAAS_ORGANISATION }}" -s "${{ env.PAAS_SPACE }}"
          cf ssh "${{ env.APP_NAME }}"-"${{ env.ENV_STUB }}" -c "cd /app && /usr/local/bundle/bin/bundle exec rails runner 'CourseLessonDataReportJob.perform_now' > /dev/null 2>&1 && cat /tmp/course_lesson_data.csv" > ~/data.csv

      - name: Upload csv to BigQuery
        shell: bash
        run: |
          bq load --format=csv --replace engage_and_learn.course_lesson_data ~/data.csv
